### ISSUE TITLE
add hls this video

### ISSUE THREAD

**Issue by xoceunder** [paulwhiting/GospelLibraryVideos#9]
add hls this video run

**Comment by paulwhiting** [comment]
Which HLS streams did you have in mind?

**Comment by xoceunder** [comment]
that's the format for live stream

**Comment by xoceunder** [comment]
You could pay for making me a job

**Comment by paulwhiting** [comment]
@xoceunder just so you understand, my Roku and FireTV channels here are designed for the sole purpose of displaying Christian multi-media in a form accessible for the most people.  If you'd like to assist my project for free then please contribute by sending me pull requests.

**Comment by paulwhiting** [comment]
Closed as unnecessary.
